version: "3"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
  server:
    build: ./patientInfoServer
    container_name: server
    ports:
      - "3001:3001"
  client:
    build: ./patientInfoClient
    container_name: client
    ports:
      - "8080:80"
